name: flutter_intl_phone_field
description: A customized Flutter TextFormField to input international phone number along with country code.
version: 0.0.1
homepage: https://github.com/rvndsngwn/flutter_intl_phone_field
repository: https://github.com/mohesu/flutter_intl_phone_field
issue_tracker: https://github.com/mohesu/flutter_intl_phone_field/issues
documentation: https://github.com/mohesu/flutter_intl_phone_field/blob/master/README.md
screenshots:
  - description: "Phone Number Picker"
    path: image-1.PNG
  - description: "Country Picker"
    path: image-2.PNG

topics:
  - flutter_intl_phone_field
  - intl_phone_field
  - international_phone_field
  - number_field

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  assets:
    - assets/flags/
